# Initial A and B matrixes generation

In [297]:
import numpy as np

K, L, T = 3, 3, 2 # A, B submatrixies
p = 29 # field (finite or np.inf)

bound = 12 # values boundaries

# sizes: size_A * width_AB and width_AB * size_B => result size_A * size_B
width_AB = 3
size_A, size_B = 9, 9

assert size_A % K == 0, 'Please, use multiples of each other numbers'
assert size_B % L == 0, 'Please, use multiples of each other numbers'

A = np.matrix(np.random.randint(0, bound, (width_AB, size_A))).T % p
B = np.matrix(np.random.randint(0, bound, (width_AB, size_B))) % p

print('Matrices A, B have been generated')
display('A = ', A)
display('B = ', B)

Matrices A, B have been generated


'A = '

matrix([[ 0,  9,  7],
        [ 4,  0,  7],
        [ 8, 11,  8],
        [ 8,  1,  8],
        [ 7,  2,  0],
        [ 1,  7,  1],
        [ 2,  0,  9],
        [ 2,  8,  6],
        [ 4,  4,  9]], dtype=int32)

'B = '

matrix([[11,  9, 11, 10,  1,  2,  1,  5,  8],
        [ 6,  1,  8,  9,  9,  4,  4,  7,  8],
        [ 9,  8,  5,  3,  5,  8, 11,  8,  2]], dtype=int32)

# Regular A and B multiplication

In [298]:
REG_MAT_MUL = A @ B % p
REG_MAT_MUL

matrix([[ 1,  7, 20, 15,  0,  5, 26,  3, 28],
        [20,  5, 21,  3, 10,  6, 23, 18, 17],
        [23,  2, 13,  0,  2,  8, 24,  7, 23],
        [21, 21, 20, 26, 28, 26, 13, 24,  1],
        [ 2,  7,  6,  1, 25, 22, 15, 20, 14],
        [ 4, 24, 14, 18, 11,  9, 11,  4,  8],
        [16,  3,  9, 18, 18, 18, 14, 24,  5],
        [ 8, 16,  0, 23, 17, 26, 13, 27,  5],
        [ 4, 25,  5, 16, 27,  9,  3,  4, 24]], dtype=int32)

# Genearating A_k, B_l, k = 1...K, l = 1...L submatrixes

In [299]:
# A submatrices
print('Submatrices A_i have been generated')
A_ = np.zeros([K, int(size_A / K), width_AB])
for i in range(K):
    A_[i] = np.split(A, K, axis = 0)[i] % p
display('A = ', A_)

# B submatrices
print('Submatrices B_i have been generated')
B_ = np.zeros([L, width_AB, int(size_B / L)])
for i in range(L):
    B_[i] = np.split(B, L, axis = 1)[i] % p
display('B = ', B_)

Submatrices A_i have been generated


'A = '

array([[[ 0.,  9.,  7.],
        [ 4.,  0.,  7.],
        [ 8., 11.,  8.]],

       [[ 8.,  1.,  8.],
        [ 7.,  2.,  0.],
        [ 1.,  7.,  1.]],

       [[ 2.,  0.,  9.],
        [ 2.,  8.,  6.],
        [ 4.,  4.,  9.]]])

Submatrices B_i have been generated


'B = '

array([[[11.,  9., 11.],
        [ 6.,  1.,  8.],
        [ 9.,  8.,  5.]],

       [[10.,  1.,  2.],
        [ 9.,  9.,  4.],
        [ 3.,  5.,  8.]],

       [[ 1.,  5.,  8.],
        [ 4.,  7.,  8.],
        [11.,  8.,  2.]]])

# Multiplication using A_k, B_l parts

In [300]:
result = np.zeros([size_A, size_B]) # we know size to be calculated
for i in range(0, A_.shape[0], 1): # for each partial A matrix
    for j in range(0, B_.shape[0], 1): # for each partial B matrix
        delta_A, delta_B = int(size_A / K), int(size_B / L)
        # calculate each result A_[i] @ B_[j] separately
        result[delta_A*i:delta_A*(i+1), delta_B*j:delta_B*(j+1)] = A_[i] @ B_[j] % p
PARTED_MAT_MUL = result
PARTED_MAT_MUL % p

array([[ 1.,  7., 20., 15.,  0.,  5., 26.,  3., 28.],
       [20.,  5., 21.,  3., 10.,  6., 23., 18., 17.],
       [23.,  2., 13.,  0.,  2.,  8., 24.,  7., 23.],
       [21., 21., 20., 26., 28., 26., 13., 24.,  1.],
       [ 2.,  7.,  6.,  1., 25., 22., 15., 20., 14.],
       [ 4., 24., 14., 18., 11.,  9., 11.,  4.,  8.],
       [16.,  3.,  9., 18., 18., 18., 14., 24.,  5.],
       [ 8., 16.,  0., 23., 17., 26., 13., 27.,  5.],
       [ 4., 25.,  5., 16., 27.,  9.,  3.,  4., 24.]])

# Check if regular mat.mul equals to partial mat.mul

In [301]:
PARTED_MAT_MUL == REG_MAT_MUL

matrix([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

# Encoding procedure

### S_t, R_t submatrices generation, t = 1...T

In [302]:
# S submatrices
print('Submatrices R_i have been generated')
R_ = np.zeros([T, int(size_A / K), width_AB])
for i in range(T):
    R_[i] = np.matrix(np.random.randint(1, bound, (int(size_A / K), width_AB))) % p
display('R_ = ', R_)

# R submatrices
print('Submatrices S_i have been generated')
S_ = np.zeros([T, width_AB, int(size_B / L)])
for i in range(T):
    S_[i] = np.matrix(np.random.randint(1, bound, (width_AB, int(size_B / L)))) % p
display('S_ = ', S_)

Submatrices R_i have been generated


'R_ = '

array([[[ 7.,  7.,  2.],
        [ 6.,  4.,  2.],
        [ 8.,  5.,  1.]],

       [[ 3.,  8.,  4.],
        [10.,  4.,  4.],
        [ 9.,  2., 10.]]])

Submatrices S_i have been generated


'S_ = '

array([[[ 1.,  3.,  7.],
        [10.,  2.,  8.],
        [ 9.,  4.,  7.]],

       [[ 5.,  1.,  3.],
        [ 3.,  9.,  8.],
        [11.,  8.,  6.]]])

# Vector of coefficients of f(x) and g(x): A1,A2,A3,R1,R2...

In [303]:
F_X = np.vstack((A_, R_)) # vertical concatination (F_X = A1,A2,A3,R1,R2)
G_X = np.vstack((B_, S_)) # vertical concatination (G_X = B1,B2,B3,S1,S2)

display('F_X = ', F_X)
display('G_X = ', G_X)

'F_X = '

array([[[ 0.,  9.,  7.],
        [ 4.,  0.,  7.],
        [ 8., 11.,  8.]],

       [[ 8.,  1.,  8.],
        [ 7.,  2.,  0.],
        [ 1.,  7.,  1.]],

       [[ 2.,  0.,  9.],
        [ 2.,  8.,  6.],
        [ 4.,  4.,  9.]],

       [[ 7.,  7.,  2.],
        [ 6.,  4.,  2.],
        [ 8.,  5.,  1.]],

       [[ 3.,  8.,  4.],
        [10.,  4.,  4.],
        [ 9.,  2., 10.]]])

'G_X = '

array([[[11.,  9., 11.],
        [ 6.,  1.,  8.],
        [ 9.,  8.,  5.]],

       [[10.,  1.,  2.],
        [ 9.,  9.,  4.],
        [ 3.,  5.,  8.]],

       [[ 1.,  5.,  8.],
        [ 4.,  7.,  8.],
        [11.,  8.,  2.]],

       [[ 1.,  3.,  7.],
        [10.,  2.,  8.],
        [ 9.,  4.,  7.]],

       [[ 5.,  1.,  3.],
        [ 3.,  9.,  8.],
        [11.,  8.,  6.]]])

# Alpha and beta arrays: alphas(K+T), betas(L+T), N servers

In [304]:
# GASP BIG (N calculation)
def get_N_GB(K, L, T):
    N = 0
    if L <= K:
        if T < K:
            N = (K + T) * (L + 1) - 1
        elif T >= K:
            N = 2 * K * L + 2 * T - 1
    if L > K:
        if T < L:
            N = (L + T) * (K + 1) - 1
        elif T >= L:
            N = 2 * K * L + 2 * T - 1
    return N

# GASP SMALL (N calculation)
def get_N_GS(K, L, T):
    N = 0
    if K <= L:
        if L == 1 and T < K:
            N = 2*K + T*T
        elif L == 1 and T >= K:
            N = K*T + K + T
        elif L >=2 and T == 1 and T < K:
            N = K*L + K + L
        elif L >=2 and T >=2 and T < K:
            N = K*L + K + L + T*T + T - 3
        elif L >= 2 and K <= T and T <= K * (L - 1) + 1:
            N = K*L + K*T + L + 2*T - 3 - ((T - 2) / K)
        elif L >= 2 and T >= K * (L - 1) + 1:
            N = 2*K*L + K*T - K + T
    if K > L:
        if K == 1 and T < L:
            N = 2*L + T*T
        elif K == 1 and T >= L:
            N = L*T + L + T
        elif K >=2 and T == 1 and T < L:
            N = K*L + K + L
        elif K >=2 and T >= 2 and T < L:
            N = K*L + K + L + T*T + T - 3
        elif K >= 2 and L <= T and T <= L * (K - 1) + 1:
            N = K*L + L*T + K + 2*T - 3 - ((T - 2) / L)
        elif K >= 2 and T >= L * (K - 1) + 1:
            N = 2*K*L + L*T - L + T
    return N

# the set of degrees
def GASP_big(K, L, T):
    if K >= L:
        a = np.zeros([K + T])
        b = np.zeros([L + T])
        for k in range(0, K, 1):
            a[k] = k
        for t in range(0, T, 1):
            a[K + t] = K * L + t

        for l in range(0, L, 1):
            b[l] = K * l
        for t in range(0, T, 1):
            b[L + t] = K * L + t

    if K < L:
        a = np.zeros([L + T])
        b = np.zeros([K + T])
        
        for l in range(0, L, 1):
            a[l] = K * l
        for t in range(0, T, 1):
            a[L + t] = K * L + t
        
        for k in range(0, K, 1):
            b[k] = k
        for t in range(0, T, 1):
            b[K + t] = K * L + t

    return a, b

# the set of degrees
def GASP_small(K, L, T):
    if K <= L:
        a = np.zeros([K + T])
        b = np.zeros([L + T])
        for k in range(0, K, 1):
            a[k] = k
        for t in range(0, T, 1):
            a[K + t] = K * L + K * t

        for l in range(0, L, 1):
            b[l] = K * l
        for t in range(0, T, 1):
            b[L + t] = K * L + t

    if K > L:
        a = np.zeros([L + T])
        b = np.zeros([K + T])

        for l in range(0, L, 1):
            a[l] = K * l
        for t in range(0, T, 1):
            a[L + t] = K * L + t
        
        for k in range(0, K, 1):
            b[k] = k
        for t in range(0, T, 1):
            b[K + t] = K * L + K * t

    return a, b

def GASP(K, L, T):
    min_KL = np.minimum(K, L)
    
    if T < min_KL:
        alp, bet = GASP_small(K, L, T)
        N = get_N_GS(K, L, T)
        print('T < min(K,L) - GASP_small, N = ', N)
        
    if T >= min_KL:
        alp, bet = GASP_big(K, L, T)
        N = get_N_GB(K, L, T)
        print('T >= min(K,L) - GASP_big, N = ', N)
        
    return alp, bet, N

# Print N, alpha and beta sets corresponding current K,L,T

In [305]:
alphas, betas, N = GASP(K = K, L = L, T = T)
display('alphas = ', alphas)
display('betas = ', betas)

T < min(K,L) - GASP_small, N =  18


'alphas = '

array([ 0.,  1.,  2.,  9., 12.])

'betas = '

array([ 0.,  3.,  6.,  9., 10.])

# Let's build the degree table

In [306]:
degree_table = np.zeros([alphas.shape[0], betas.shape[0]], dtype = np.int)

for i in range(alphas.shape[0]):
    for j in range(betas.shape[0]):
        degree_table[i,j] = alphas[i] + betas[j]
        
display('degree_table =', degree_table)

'degree_table ='

array([[ 0,  3,  6,  9, 10],
       [ 1,  4,  7, 10, 11],
       [ 2,  5,  8, 11, 12],
       [ 9, 12, 15, 18, 19],
       [12, 15, 18, 21, 22]])

# The set of unique polnom's powers

In [307]:
J = np.unique(degree_table.reshape([degree_table.size]))

print('All degrees in table = ', J)

All degrees in table =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 15 18 19 21 22]


# Set of x points for N servers

In [308]:
x = np.arange(1, N+1).reshape([N,1]) @ np.ones([1,K+T])
x

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11.],
       [12., 12., 12., 12., 12.],
       [13., 13., 13., 13., 13.],
       [14., 14., 14., 14., 14.],
       [15., 15., 15., 15., 15.],
       [16., 16., 16., 16., 16.],
       [17., 17., 17., 17., 17.],
       [18., 18., 18., 18., 18.]])

# Set of alphas and betas for N servers

In [309]:
alfa = np.ones([N,1]) @ alphas.reshape([1,alphas.size])
beta = np.ones([N,1]) @ betas.reshape([1,betas.size])
alfa

array([[ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.],
       [ 0.,  1.,  2.,  9., 12.]])

# Set of x^alphas and x^betas for N servers

In [310]:
f_x_coefs = x**alfa % p
g_x_coefs = x**beta  % p
f_x_coefs

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  4., 19.,  7.],
       [ 1.,  3.,  9., 21., 16.],
       [ 1.,  4., 16., 13., 20.],
       [ 1.,  5., 25.,  4.,  7.],
       [ 1.,  6.,  7., 22., 25.],
       [ 1.,  7., 20., 20., 16.],
       [ 1.,  8.,  6., 15., 24.],
       [ 1.,  9., 23.,  6., 24.],
       [ 1., 10., 13., 18., 20.],
       [ 1., 11.,  5.,  2., 23.],
       [ 1., 12., 28., 12.,  1.],
       [ 1., 13., 24.,  5., 23.],
       [ 1., 14., 22.,  3., 25.],
       [ 1., 15., 22., 26., 25.],
       [ 1., 16., 24., 24., 23.],
       [ 1., 17., 28., 17.,  1.],
       [ 1., 18.,  5., 27., 23.]])

# Polynoms f(x) and g(x) for each server (separate values, not sum)

In [311]:
m = int(size_A / K) # size of submatrixes A
n = int(size_B / L) # size of submatrixes B

In [312]:
f_x = np.zeros([N, alphas.size, m,n])
g_x = np.zeros([N, betas.size, m,n])

for i in range(N):
    for j in range(5):
        f_x[i,j] = f_x_coefs[i,j] * F_X[j] % p
        g_x[i,j] = g_x_coefs[i,j] * G_X[j] % p
        
display('f_x[i] = ', f_x[1].astype('int'))

'f_x[i] = '

array([[[ 0,  9,  7],
        [ 4,  0,  7],
        [ 8, 11,  8]],

       [[16,  2, 16],
        [14,  4,  0],
        [ 2, 14,  2]],

       [[ 8,  0,  7],
        [ 8,  3, 24],
        [16, 16,  7]],

       [[17, 17,  9],
        [27, 18,  9],
        [ 7,  8, 19]],

       [[21, 27, 28],
        [12, 28, 28],
        [ 5, 14, 12]]])

# Polynoms f(x) and g(x) for each server - sum result along 0 axis: f(a_n) and g(a_n), a_n = 1...N 

In [313]:
f_x_i = np.zeros([N,m,n])
g_x_i = np.zeros([N,m,n])
for i in range(N):
    f_x_i[i] = f_x[i].sum(axis = 0) % p
    g_x_i[i] = g_x[i].sum(axis = 0) % p

display('f_x_i[i] = ', f_x_i[1].astype('int'))
display('f_x_i[i]*g_x_i[i] = ', (f_x_i[1]*g_x_i[1]))

'f_x_i[i] = '

array([[ 4, 26,  9],
       [ 7, 24, 10],
       [ 9,  5, 19]])

'f_x_i[i]*g_x_i[i] = '

array([[ 64., 676.,  27.],
       [  0.,  48., 220.],
       [189.,  60., 133.]])

# Server calculations imitation: h(a_n) = f(a_n) * g(a_n), a_n = 1...N

In [314]:
h_i = np.zeros([N,m,n])
for server in range(N):
    h_i[server] = f_x_i[server] * g_x_i[server] % p
    
# h_i = h_i.reshape([N,1])
display('h_i = ', h_i)

'h_i = '

array([[[ 9., 11.,  2.],
        [ 0., 11., 17.],
        [14.,  0.,  0.]],

       [[ 6.,  9., 27.],
        [ 0., 19., 17.],
        [15.,  2., 17.]],

       [[ 2.,  5., 28.],
        [28., 21.,  2.],
        [11., 18.,  0.]],

       [[ 7., 17., 22.],
        [18., 10., 23.],
        [ 4., 26., 10.]],

       [[24., 17., 24.],
        [17., 28.,  5.],
        [28., 13., 17.]],

       [[ 6.,  6., 25.],
        [16.,  8.,  8.],
        [ 7.,  8.,  1.]],

       [[27., 27., 22.],
        [ 2., 19., 11.],
        [26., 17., 11.]],

       [[ 9., 15., 26.],
        [ 2., 25., 11.],
        [18., 12., 16.]],

       [[ 0., 23., 22.],
        [21., 27., 19.],
        [13.,  7.,  0.]],

       [[ 7., 24., 11.],
        [24., 26.,  6.],
        [12., 23., 20.]],

       [[18., 25., 19.],
        [22.,  3., 12.],
        [11.,  4.,  0.]],

       [[ 4.,  6., 12.],
        [21., 25.,  0.],
        [ 5., 14., 27.]],

       [[24., 14., 27.],
        [ 8.,  8., 26.],
        [ 2., 19.,  6.]],


# Decoding using inverse Vandermond matrix

In [315]:
# find all numbers from zero to max value in the degree table
numbers_range = np.arange(0, max(J)+1).astype('int')
print('Range 0 to max power =', numbers_range)

# find all numbers from the degree table
degree_range_in_table = J
print('All powers in table = ', degree_range_in_table)

# find all numbers from the numbers_range which are not in the degree table (to delete)
degree_to_delete = np.delete(numbers_range, obj = degree_range_in_table, axis = 0)
print('Powers with zero coefficients = ', degree_to_delete+1)

Range 0 to max power = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
All powers in table =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 15 18 19 21 22]
Powers with zero coefficients =  [14 15 17 18 21]


In [316]:
vand = np.zeros([N,int(max(J)+1)])
for a in range(1, N+1):
    vand[a-1] = np.array([a**x for x in range(int(max(J)+1))]) % p
vand

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8., 16.,  3.,  6., 12., 24., 19.,  9., 18.,  7.,
        14., 28., 27., 25., 21., 13., 26., 23., 17.,  5.],
       [ 1.,  3.,  9., 27., 23., 11.,  4., 12.,  7., 21.,  5., 15., 16.,
        19., 28., 26., 20.,  2.,  6., 18., 25., 17., 22.],
       [ 1.,  4., 16.,  6., 24.,  9.,  7., 28., 25., 13., 23.,  5., 20.,
        22.,  1.,  4., 16.,  6., 24.,  9.,  7., 28., 25.],
       [ 1.,  5., 25.,  9., 16., 22., 23., 28., 24.,  4., 20., 13.,  7.,
         6.,  1.,  5., 25.,  9., 16., 22., 23., 28., 24.],
       [ 1.,  6.,  7., 13., 20.,  4., 24., 28., 23., 22., 16.,  9., 25.,
         5.,  1.,  6.,  7., 13., 20.,  4., 24., 28., 23.],
       [ 1.,  7., 20., 24., 23., 16., 25.,  1.,  7., 20., 24., 23., 16.,
        25.,  1.,  7., 20., 24., 23., 16., 25.,  1.,  7.],
       [ 1.,  8.,  6., 19.,  7., 27., 13., 17., 20., 15.,  4.,  3., 24.,
   

In [317]:
cut_vand = np.delete(vand, obj = degree_to_delete, axis = 1) # delete places with zero coeffs of x_i
print(cut_vand.shape)
cut_vand

(18, 18)


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8., 16.,  3.,  6., 12., 24., 19.,  9., 18.,  7.,
        27., 13., 26., 17.,  5.],
       [ 1.,  3.,  9., 27., 23., 11.,  4., 12.,  7., 21.,  5., 15., 16.,
        26.,  6., 18., 17., 22.],
       [ 1.,  4., 16.,  6., 24.,  9.,  7., 28., 25., 13., 23.,  5., 20.,
         4., 24.,  9., 28., 25.],
       [ 1.,  5., 25.,  9., 16., 22., 23., 28., 24.,  4., 20., 13.,  7.,
         5., 16., 22., 28., 24.],
       [ 1.,  6.,  7., 13., 20.,  4., 24., 28., 23., 22., 16.,  9., 25.,
         6., 20.,  4., 28., 23.],
       [ 1.,  7., 20., 24., 23., 16., 25.,  1.,  7., 20., 24., 23., 16.,
         7., 23., 16.,  1.,  7.],
       [ 1.,  8.,  6., 19.,  7., 27., 13., 17., 20., 15.,  4.,  3., 24.,
        21., 22.,  2., 12.,  9.],
       [ 1.,  9., 23.,  4.,  7.,  5., 16., 28., 20.,  6., 25., 22., 24.,
         9.,  7.,  5., 28., 20.],
       [ 1., 10., 13., 14., 24.,  8.,

In [318]:
from numpy import linalg as LA

LA.det(cut_vand) % p

26.0

In [319]:
Vinv = np.linalg.inv(cut_vand)
Vinv

array([[ 1.06687752e+00, -8.22498370e-03,  4.34866447e-03,
         2.50839673e-02, -1.18793796e-02, -3.08029775e-02,
         1.19789183e-02,  2.82572012e-03,  2.12595574e-02,
         1.73552147e-02, -6.51815356e-03, -2.62098934e-02,
        -3.75320467e-03, -2.93344339e-02, -1.39679606e-02,
        -4.87440071e-03,  2.78390678e-03, -1.69480807e-02],
       [ 4.23459161e-03,  3.57888004e-03, -2.62123124e-02,
        -4.74768330e-02,  1.47637950e-03,  6.00343480e-02,
        -3.99933528e-02, -2.71229461e-02, -5.20846686e-02,
        -3.35938556e-02,  4.24535685e-03,  4.61531689e-02,
         7.10323978e-03,  6.22534761e-02,  1.66010335e-02,
         4.81122701e-03, -1.29178664e-02,  2.89101335e-02],
       [-6.67068355e-03, -8.77152260e-03,  1.78087551e-02,
         9.82014414e-03, -6.95971952e-03, -9.64014171e-03,
         1.06170138e-02, -1.39835276e-02,  9.82114500e-03,
         1.72833701e-02, -4.67264570e-02,  1.38318710e-02,
        -6.04618065e-03,  4.72138302e-02, -1.41422917e

In [320]:
h_i.shape

(18, 3, 3)

In [322]:
np.round(cut_vand @ Vinv) #% p

array([[ 1., -0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0., -0.,  0.,
         0.,  0., -0., -0.,  0.],
       [ 0.,  1.,  0.,  0., -0., -0., -0., -0.,  0.,  0.,  0., -0.,  0.,
        -0.,  0.,  0.,  0., -0.],
       [-0., -0.,  1., -0.,  0., -0.,  0.,  0., -0.,  0.,  0., -0.,  0.,
        -0.,  0.,  0.,  0., -0.],
       [ 0.,  0., -0.,  1.,  0., -0., -0.,  0., -0.,  0.,  0.,  0.,  0.,
         0.,  0., -0.,  0., -0.],
       [-0.,  0., -0.,  0.,  1., -0., -0.,  0., -0.,  0.,  0., -0., -0.,
        -0., -0.,  0.,  0., -0.],
       [-0., -0.,  0.,  0., -0.,  1., -0.,  0.,  0., -0.,  0., -0., -0.,
        -0.,  0., -0., -0., -0.],
       [-0.,  0.,  0., -0., -0.,  0.,  1., -0., -0., -0.,  0.,  0., -0.,
         0., -0.,  0., -0.,  0.],
       [-0.,  0.,  0., -0.,  0.,  0.,  0.,  1., -0.,  0., -0., -0.,  0.,
         0., -0., -0.,  0.,  0.],
       [-0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  1.,  0., -0.,  0., -0.,
         0., -0.,  0., -0.,  0.],
       [-0.,  0.,  0.,  0., -0.,  0.,

In [323]:
np.round(Vinv @ cut_vand) #% p

array([[ 1., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0.],
       [ 0.,  1.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0., -0.,  0.,  0.,  0., -0., -0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [-0., -0., -0.,  0.,  1., -0., -0., -0., -0.,  0., -0., -0., -0.,
        -0., -0.,  0., -0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0., -0.,  0.,  0.,  0., -0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [-0., -0., -0., -0., -0., -0.,  1., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0.],
       [-0., -0., -0., -0., -0., -0., -0.,  1., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0.],
       [-0., -0., -0., -0.,  0., -0., -0.,  0.,  1.,  0.,  0.,  0., -0.,
        -0., -0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,

In [326]:
C = np.zeros([N,m,n])

for i in range(m):
    for j in range(n):
        C[:,i,j] = np.round(Vinv @ h_i[:,i,j])# % p  # np.linalg.solve(Vinv, h[:,i,j]) % p
#         C[:,i,j] = np.round(h_i[:,i,j] @ Vinv ) % p  # np.linalg.solve(Vinv, h[:,i,j]) % p

C.astype('int')

array([[[ 9, 12,  1],
        [-1, 11, 18],
        [14,  0, -1]],

       [[ 0, -2, -1],
        [ 1, -1, -1],
        [-1, -1,  0]],

       [[-1,  0, -1],
        [ 1,  1, -1],
        [-1,  2,  0]],

       [[-1, -1,  0],
        [ 1,  1, -2],
        [-1, -1,  0]],

       [[-1,  1,  0],
        [ 0,  1, -4],
        [-1,  2,  1]],

       [[ 1,  1,  1],
        [-1,  0,  0],
        [ 1,  0,  0]],

       [[ 0,  1,  0],
        [ 0,  0, -1],
        [ 0,  0,  0]],

       [[ 0,  1,  1],
        [ 0,  1, -1],
        [ 0,  0,  1]],

       [[-4, -2, -2],
        [ 2,  2, -7],
        [-2,  2,  1]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  1,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[-1, -1,  0],
        [ 0,  1, -2],
        [ 0,  0,  0]],

       [[ 3,  1,  2],
        [-2, -3,  7],
        [ 2, -2, -1]],

       [[-2,  1,  0],
        [ 0,  1, -2],
        [-1,  2,  1]],

       [[ 1,  0,  1],
        [-1, -1,  2],
    

In [327]:
multivand = np.zeros([N,N,m,n])

for i in range(N):
    for j in range(N):
        multivand[i,j,:,:] = Vinv[i,j]# % p
        
multivand

array([[[[ 1.06687752e+00,  1.06687752e+00,  1.06687752e+00],
         [ 1.06687752e+00,  1.06687752e+00,  1.06687752e+00],
         [ 1.06687752e+00,  1.06687752e+00,  1.06687752e+00]],

        [[-8.22498370e-03, -8.22498370e-03, -8.22498370e-03],
         [-8.22498370e-03, -8.22498370e-03, -8.22498370e-03],
         [-8.22498370e-03, -8.22498370e-03, -8.22498370e-03]],

        [[ 4.34866447e-03,  4.34866447e-03,  4.34866447e-03],
         [ 4.34866447e-03,  4.34866447e-03,  4.34866447e-03],
         [ 4.34866447e-03,  4.34866447e-03,  4.34866447e-03]],

        ...,

        [[-4.87440071e-03, -4.87440071e-03, -4.87440071e-03],
         [-4.87440071e-03, -4.87440071e-03, -4.87440071e-03],
         [-4.87440071e-03, -4.87440071e-03, -4.87440071e-03]],

        [[ 2.78390678e-03,  2.78390678e-03,  2.78390678e-03],
         [ 2.78390678e-03,  2.78390678e-03,  2.78390678e-03],
         [ 2.78390678e-03,  2.78390678e-03,  2.78390678e-03]],

        [[-1.69480807e-02, -1.69480807e-02, -1

In [328]:
r = []

for i in range(m):
    for j in range(n):
        r.append(np.round(multivand[:,:,i,j] @ C[:,i,j]))
r

[array([10.,  0., -0., -0., -1., -0., -0., -0., -1., -0., -0., -0.,  1.,
        -1.,  0.,  1.,  1., -0.]),
 array([13.,  0., -0.,  0., -0., -0., -0., -0.,  0., -0., -0., -0.,  0.,
        -0.,  0.,  0., -0.,  0.]),
 array([ 1.,  0., -0.,  0., -0., -0., -0., -0., -0., -0., -0., -0.,  0.,
        -0.,  0.,  0.,  0., -0.]),
 array([-1., -0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,
         0., -0., -0., -0.,  0.]),
 array([12., -0.,  0.,  0.,  0., -0., -0.,  0.,  0., -0., -0.,  0., -1.,
         0., -0., -1., -1.,  0.]),
 array([19.,  0., -0., -0., -1., -0., -0., -0., -1., -0., -1., -1.,  1.,
        -1.,  1.,  2.,  1., -0.]),
 array([15.,  0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,  0.,
        -1.,  0.,  1.,  0., -0.]),
 array([-0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0., -1.,
         0., -0., -1., -1.,  0.]),
 array([-1., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0., -0.,
         0., -0., -0., -0.,  0.])]

In [329]:
b = np.zeros([N,m,n])
step = 0
for i in range(m):
    for j in range(n):
        b[:,i,j] = r[step]
        step += 1
b

array([[[10., 13.,  1.],
        [-1., 12., 19.],
        [15., -0., -1.]],

       [[ 0.,  0.,  0.],
        [-0., -0.,  0.],
        [ 0.,  0., -0.]],

       [[-0., -0., -0.],
        [ 0.,  0., -0.],
        [-0.,  0.,  0.]],

       [[-0.,  0.,  0.],
        [-0.,  0., -0.],
        [-0.,  0.,  0.]],

       [[-1., -0., -0.],
        [ 0.,  0., -1.],
        [-0.,  0.,  0.]],

       [[-0., -0., -0.],
        [ 0., -0., -0.],
        [-0.,  0.,  0.]],

       [[-0., -0., -0.],
        [ 0., -0., -0.],
        [-0.,  0.,  0.]],

       [[-0., -0., -0.],
        [ 0.,  0., -0.],
        [-0.,  0.,  0.]],

       [[-1.,  0., -0.],
        [ 0.,  0., -1.],
        [-0.,  1.,  0.]],

       [[-0., -0., -0.],
        [ 0., -0., -0.],
        [-0.,  0., -0.]],

       [[-0., -0., -0.],
        [ 0., -0., -1.],
        [-0.,  0.,  0.]],

       [[-0., -0., -0.],
        [ 0.,  0., -1.],
        [-0.,  0.,  0.]],

       [[ 1.,  0.,  0.],
        [-0., -1.,  1.],
        [ 0., -1., -0.]],


In [330]:
REG_MAT_MUL

matrix([[ 1,  7, 20, 15,  0,  5, 26,  3, 28],
        [20,  5, 21,  3, 10,  6, 23, 18, 17],
        [23,  2, 13,  0,  2,  8, 24,  7, 23],
        [21, 21, 20, 26, 28, 26, 13, 24,  1],
        [ 2,  7,  6,  1, 25, 22, 15, 20, 14],
        [ 4, 24, 14, 18, 11,  9, 11,  4,  8],
        [16,  3,  9, 18, 18, 18, 14, 24,  5],
        [ 8, 16,  0, 23, 17, 26, 13, 27,  5],
        [ 4, 25,  5, 16, 27,  9,  3,  4, 24]], dtype=int32)